### PR TITLE
Upgrade to LDTK v1.0.0

### PR DESCRIPTION
**Pull request by PsichiX**
- added schema v1.0.0
- added support for enabling older versions with features (if that's not ok, maybe we should make crate versions match schema version numbers? imo features might be good to allow devs to quickly change versions without downloading different crate versions)

### CODE REVIEW

**Comment by PsichiX** [comment]
tbh i wonder if instead of putting all versions behind features, maybe it would be better to just include all schemes as modules to make people that do asset converters (like me) to be able to use all of them (typical use case of making assimp-like tool)

**Comment by estivate** [comment]
I don't personally have a use case for supporting multiple versions at once, but sounds like you do. This approach seems pretty straightforward, but if the module approach would be more useful to you I can hold off on merging this PR until we have time to check that out?

**Comment by PsichiX** [comment]
great! i'm working on a solution for multiple versions support

**Comment by PsichiX** [comment]
actually, you know what - after thinking about it, i'm more inclined to just drop multiple versions support entirely, because upgrading projects made with older versions is cheaper than all that effort with supporting versioned projects 🤔
i'll reset changes and just add version 1.0.0 and 1.1.0

**Pull request closed without merging**
